### ISSUE TITLE
topology complection does not connect two node templates, although suitable relationship types ara available

### ISSUE THREAD

**Issue by F7502** [winery/winery#1]
Example scenario:
A topology contains one node template that has one requirement. In the repository there is another node type available that offers a matching capability. The repository also contains a relationship type that has no restrictions on source and target nodes (i.e. no defined node types, no requirements and capabilities). When starting the topology completion, the topology is completed by adding a second node template that fulfills the requirements of the first node, but the two nodes are not connected with any relationship template.

I located the error at line 78 in org.eclipse.winery.topologymodeler.addons.topologycompleter.helper.NodeTemplateConnector, the line should be:

if (rt.getValidSource() == null && rt.getValidTarget() == null) {

-> the second "==" has been a "!=" before.

After changing this and then running the same example again, everything worked as expected (i.e. the topology gets completed and the two node templates are now connected using the available relationship type).

**Comment by hirmerpl** [comment]
Thanks for the hint! It should of course be "== null"... maybe a copy&paste issue. 
Furthermore, a test case should be added to cover this. Usually, the valid source and valid target elements are not filled in (e.g., hosted on, deployed on etc.).

I will look into it.

**Comment by hirmerpl** [comment]
Bug is fixed & committed to the winery eclipse repository

**Comment by koppor** [comment]
I pushed it to here (ec21d9afaf46). @hirmerpl You can use "fixes #1" in the commit message (and manually push to github, too until the automatic mirroring is setup)
